# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        scoped_clients:
            twentyI_api:
                scope: 'https://api\.20i\.com'
                #base_uri: 'https://api.20i.com/'
                auth_bearer: 'Bearer Y2M1NTE0YjE3ZWU2M2ZiMjU='

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
